# Generated by Django 5.1.1 on 2026-05-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='wger_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exercisecategory',
            name='wger_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
