# Generated by Django 5.1.1 on 2026-05-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_exercise_wger_id_exercisecategory_wger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='wger_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
