# Generated by Django 5.1.1 on 2026-05-02 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wger_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('calories', models.DecimalField(decimal_places=2, help_text='kcal per 100g', max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, help_text='g per 100g', max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, help_text='g per 100g', max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, help_text='g per 100g', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Desayuno'), ('LUNCH', 'Almuerzo'), ('DINNER', 'Cena'), ('SNACK', 'Snack/Otros')], max_length=20)),
                ('food_name', models.CharField(max_length=200)),
                ('amount_g', models.DecimalField(decimal_places=2, help_text='Cantidad en gramos', max_digits=7)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to='clients.client')),
            ],
        ),
    ]
