# Generated by Django 5.1.1 on 2026-05-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddField(
            model_name='nutritionlog',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Carbohidratos (g)'),
        ),
        migrations.AddField(
            model_name='nutritionlog',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Grasas (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='amount_g',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad en gramos', max_digits=7, verbose_name='Cantidad (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Calorías (kcal)'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='food_name',
            field=models.CharField(max_length=200, verbose_name='Alimento'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Desayuno'), ('LUNCH', 'Almuerzo'), ('DINNER', 'Cena'), ('SNACK', 'Snack/Otros')], max_length=20, verbose_name='Tipo de Comida'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Proteína (g)'),
        ),
    ]
