# Generated by Django 5.1.1 on 2026-04-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
